// Dialog graph (DDX) data layer for the editor.
//
// Betrayal at Krondor's dialog system is a scripting VM: every scene bark, shop
// transaction, NPC conversation, cipher puzzle and party-stat change is a DDX
// bytecode record. Records reference each other by key (bit-31 set) or by raw
// file offset (bit-31 clear) to form a graph. This module parses ALL 32
// DIAL_Z<nn>.DDX partitions into a single graph keyed by (fileNumber, offset)
// and layers component/root/decoder services on top for the Phase-B graph UI.
//
// Node identity = (fileNumber, offset). Directory keys are ALIASES onto nodes.
// The census this module reproduces: 8184 nodes, 8452 edges, 1250 components,
// giant = 5362 nodes.

// ---- addressing --------------------------------------------------------------

/** Target-key bit 31: SET = global node-id key; CLEAR = raw same-file offset. */
const KEY_FLAG = 0x80000000;
const KEY_MASK = 0x7fffffff;

/** key / 100000 = partition file number (DIALOG.C:127). */
const KEY_FILE_DIVISOR = 100000;

/** Cipher (Moredhel wordlock) key base: key = base + puzzleId - 1 (CIPHER.C:65). */
const CIPHER_KEY_BASE = 0x19F0A1;
/** Wordlock cipher keys occupy this half-open range (DIAL_Z17, 163 blobs). */
const CIPHER_KEY_MIN = CIPHER_KEY_BASE;
const CIPHER_KEY_MAX = CIPHER_KEY_BASE + 1000;

/**
 * Engine-hardcoded dialog keys — the literal-argument dialog_play_record() calls
 * in bak/SRC. Generated by grepping the engine source (see the report); these
 * are external roots the world data never names. 255 distinct.
 */
const ENGINE_KEYS = [
  11, 12, 13, 14, 15, 31, 32, 33, 34, 35, 47, 63,
  64, 65, 66, 67, 68, 71, 78, 79, 81, 82, 83, 84,
  85, 86, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100,
  101, 105, 107, 110, 111, 112, 113, 114, 115, 116, 117, 118,
  119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
  131, 132, 133, 134, 135, 136, 137, 139, 140, 141, 142, 143,
  144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
  157, 158, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174,
  175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186,
  187, 188, 189, 190, 191, 192, 194, 195, 197, 198, 199, 200,
  201, 202, 203, 204, 205, 206, 209, 212, 215, 216, 223, 224,
  225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
  237, 238, 239, 240, 245, 246, 247, 250, 251, 252, 254, 255,
  256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
  268, 269, 276, 277, 303, 304, 305, 306, 311, 312, 315, 316,
  317, 322, 323, 325, 326, 329, 330, 331, 332, 333, 334, 336,
  300029, 300030, 1300061, 1300062, 1300063, 1300064, 1300065, 1300067, 1300074, 1300075, 1300076, 1300078,
  1300079, 1300080, 1300081, 1300082, 1800001, 1800002, 1800003, 1800004, 1800005, 1800006, 1800007, 1800008,
  1800009, 1800010, 1800012, 1800014, 1800017, 1800019, 1800020, 1800021, 1800022, 1800023, 1800025, 1800026,
  1800027, 1800028, 1800029, 1800030, 1800031, 1800032, 1800033, 1800034, 1800035, 1800036, 1800037, 1800042,
  1800043, 1800044, 1800046, 1800047, 1800048, 1800049, 1800050, 1800051, 1900017, 2000023, 2400027, 2400028,
  2400029, 2400030, 2400031,
];

/** DEF payload fields that carry a dialog key, per DEF kind (schema.js order). */
const DEF_DIALOG_FIELDS = [
  { kind: 0, names: ['dlgKey'] },                 // BKGR @6
  { kind: 1, names: ['entryDlgKey', 'scoutDlgKey'] }, // COMB @6/@0xA
  { kind: 3, names: ['dlgKey'] },                 // DIAL @2
  { kind: 6, names: ['dlgKey'] },                 // TOWN @6
  { kind: 7, names: ['entryDlgKey', 'scoutDlgKey'] }, // TRAP @6/@0xA
  { kind: 8, names: ['promptDlgKey', 'entryDlgKey'] }, // ZONE @9/@0xD
  { kind: 11, names: ['dlgKey'] },                // BLOC @2
];

// ---- state-name decoding ------------------------------------------------------

/** gstate id of the chapter counter (30007); entries `cond == 0x7537` gate on it. */
const CHAPTER_STATE_ID = 0x7537;

/**
 * The PAGE_THRU / "END OF DIALOG PATH" developer gate (rendered as
 * keyword-asked 347). Each zone-30 conversation ends at a marker node whose
 * forward edge is gated by this cond; the flag is only ever set by the dev
 * paging tool, never in normal play, so in real gameplay the marker's else
 * arm returns. The forward-closure can't evaluate flags, so following this
 * edge threads every conversation into the next (Phillip's tree bleeds into
 * Sumani's, etc.). Skipped by default in outEdges unless dev paths are shown.
 */
const PAGE_THRU_COND = 7847;

/** The 0x75xx scalar switch names (id - 0x7530 = case). */
const STATE_7530_NAMES = {
  0x7530: 'argCount', 0x7531: 'gold/10', 0x7532: 'gold', 0x7533: 'canAfford',
  0x7534: 'set-party-speaker', 0x7535: 'party-speaker', 0x7536: 'rest-marker',
  0x7537: 'chapter', 0x7538: 'set-npc-speaker', 0x7539: 'night', 0x753a: 'day',
  0x753c: 'hour', 0x753d: 'dialogResult', 0x753e: 'goldCost', 0x753f: 'value',
  0x7540: 'combatExitReq', 0x7541: 'worldExitReq', 0x7542: 'auxValue',
  0x7543: 'zoneId', 0x754d: 'popupRetry',
};

/** Return a short human name for a gstate event id (docs §5). */
export function stateName(id) {
  const v = id >>> 0;
  if (v in STATE_7530_NAMES) return STATE_7530_NAMES[v];
  if (v >= 0x7544 && v <= 0x754c) return `is-chapter-${v - 0x7544 + 1}`;
  if (v >= 7500 && v <= 8491) return `keyword-asked ${v - 7500}`;
  if (v >= 56000 && v % 10 === 0) return `bitmap-row ${(v - 56000) / 10}`;
  if (v >= 56000) return `chapter-flag byte ${(v - 56000) / 10 | 0}`;
  if (v >= 7000 && v <= 7259) return `door-open ${v - 7000}`;
  if (v >= 6700 && v <= 6999) return `topic-inhibited ${v - 6700}`;
  if (v >= 6480 && v <= 6499) return `town-visited ${v - 6480}`;
  if (v >= 5220) return `encounter-fought ${v - 5220}`;
  if (v >= 400 && v <= 5199) return `hotspot-done ${v - 400}`;
  if (v === 0) return 'always';
  return `flag ${hex(v)}`;
}

// ---- opcode names -------------------------------------------------------------

/** opcode -> short assigned name. */
const OP_NAMES = {
  0: 'nop', 1: 'set-speaker-name', 2: 'give', 3: 'take', 4: 'set-state',
  5: 'preload-sprites', 6: 'style-rect', 7: 'world-action', 8: 'stat-delta',
  9: 'stat-modify', 10: 'stat-query', 11: 'sfx', 12: 'sfx/music',
  13: 'advance-time', 14: 'event+timer', 15: 'free-images', 16: 'chain',
  17: 'set-roster', 18: 'heal', 19: 'party-bit', 20: 'teleport',
  21: 'end', 22: 'timer', 23: 'consume-item',
};

/** op-7 evtcond sub-action names, keyed by a1 (docs §4.4). */
const EVTCOND_ACTIONS = {
  0: 'pay gold', 1: 'earn gold', 2: 'repair armor', 3: 'complete encounter',
  4: 'mark defended', 5: 'spawn+clone', 6: 'spawn+clone', 7: 'add value',
  8: 'gamble', 9: 'bless weapons', 10: 'spawn two + gift', 11: 'raise retry floor',
  12: 'request hotspot', 13: 'reset timers', 14: 'empty cache',
  15: 'modify combatant', 16: 'share spellbooks',
};

// ---- low-level parse ---------------------------------------------------------

function hex(n) { return '0x' + (n >>> 0).toString(16).toUpperCase(); }

/** File number for a global node-id key. */
export function keyToFile(key) {
  return Math.floor((key & KEY_MASK) / KEY_FILE_DIVISOR);
}

/** DIAL_Z<nn>.DDX resource name for a file number. */
function dialFileName(fileNumber) {
  return `DIAL_Z${String(fileNumber).padStart(2, '0')}.DDX`;
}

/**
 * Parse the header + entries + ops + body of one DDX record at `off` in `view`.
 * Returns a node object (without identity/graph fields), or null if truncated.
 */
function parseRecord(view, off) {
  if (off < 0 || off + 9 > view.byteLength) return null;
  const style = view.getUint8(off);
  const speakerId = view.getUint16(off + 1, true);
  const flags = view.getUint16(off + 3, true);
  const nEntries = view.getUint8(off + 5);
  const nOps = view.getUint8(off + 6);
  const bodyLen = view.getUint16(off + 7, true);

  let p = off + 9;
  const entries = [];
  for (let i = 0; i < nEntries; i++, p += 10) {
    if (p + 10 > view.byteLength) break;
    entries.push({
      cond: view.getUint16(p, true),
      min: view.getUint16(p + 2, true),
      max: view.getUint16(p + 4, true),
      target: view.getUint32(p + 6, true),
    });
  }
  const ops = [];
  for (let i = 0; i < nOps; i++, p += 10) {
    if (p + 10 > view.byteLength) break;
    ops.push({
      op: view.getUint16(p, true),
      a1: view.getInt16(p + 2, true),
      a2: view.getInt16(p + 4, true),
      a3: view.getInt16(p + 6, true),
      a4: view.getInt16(p + 8, true),
    });
  }
  const textBytes = [];
  const bodyEnd = Math.min(p + bodyLen, view.byteLength);
  for (let i = p; i < bodyEnd; i++) {
    const c = view.getUint8(i);
    if (c === 0) break;
    textBytes.push(c);
  }
  return { style, speakerId, flags, nEntries, nOps, bodyLen, entries, ops, textBytes };
}

/** op-0x10 pushed follow-up key = *(u32*)&op.a1 (a1 lo word, a2 hi word). */
function op16Key(op) {
  return (((op.a2 & 0xffff) << 16) | (op.a1 & 0xffff)) >>> 0;
}

// ---- node id -----------------------------------------------------------------

/** Composite node id string "file:offset". */
function nodeId(fileNumber, offset) { return `${fileNumber}:${offset}`; }

// ---- DialogDb ----------------------------------------------------------------

/**
 * The parsed dialog graph plus component/root/decoder services. Build via
 * loadDialogDb(); everything is precomputed once and cached.
 */
export class DialogDb {
  constructor() {
    /** @type {Map<string, Object>} nodeId -> node */
    this.nodes = new Map();
    /** @type {Map<number, Object>} global directory key -> node */
    this.byKey = new Map();
    /** @type {Map<number, {view:DataView, dir:Map<number,number>}>} */
    this._files = new Map();
    /** @type {Object[]} sorted components (largest first). */
    this.components = [];
    /** @type {Map<string,number>} nodeId -> component index. */
    this._compOf = new Map();
    /** @type {Map<string,{cond:number,dangling:number,dangling_off:number}>} */
    this.stats = {};
    /** KEYWORD.DAT decoder, or null. */
    this.keywords = null;
    this._danglingKeys = [];
  }

  // -- node access ----------------------------------------------------------

  /** Node for a directory key (bit-31 masked automatically), or null. */
  nodeByKey(key) {
    return this.byKey.get((key & KEY_MASK) >>> 0) || null;
  }

  /** Node by its (fileNumber, offset) identity, or null. */
  nodeByOffset(fileNumber, offset) {
    return this.nodes.get(nodeId(fileNumber, offset)) || null;
  }

  /**
   * Resolve a raw target value read from a source node into the destination
   * node. bit-31 CLEAR = same-file offset (uses sourceFile); SET = global key.
   * Returns {node, kind:'off'|'key', file, offset|key} or null (zero/dangling).
   */
  resolveTarget(sourceFile, raw) {
    const masked = (raw & KEY_MASK) >>> 0;
    if (masked === 0) return null;
    if ((raw & KEY_FLAG) === 0) {
      const node = this.nodeByOffset(sourceFile, masked);
      return node ? { node, kind: 'off', file: sourceFile, offset: masked } : null;
    }
    const node = this.nodeByKey(masked);
    return node ? { node, kind: 'key', key: masked } : null;
  }

  // -- components -----------------------------------------------------------

  /** Component object for a directory key (via its node), or null. */
  componentFor(key) {
    const node = this.nodeByKey(key);
    if (!node) return null;
    return this.components[this._compOf.get(node.id)] || null;
  }

  /** Component object containing a node, or null. */
  componentForNode(node) {
    if (!node) return null;
    return this.components[this._compOf.get(node.id)] || null;
  }

  // -- roots ----------------------------------------------------------------

  /** External roots whose node lives in a given component (by index). */
  rootsFor(componentId) {
    const comp = this.components[componentId];
    if (!comp) return [];
    return comp.roots;
  }

  // -- graph extraction (for the UI) ----------------------------------------

  /**
   * A render-ready sub-graph. Accepts a component index (number), a hub
   * neighborhood spec {hubKey, depth}, or a forward-closure spec {forwardFrom}.
   * Returns {nodes, edges} where nodes carry display fields and edges carry a
   * label + kind. The forward closure is UNCAPPED — it follows every edge to full
   * reachability, so opening a conversation that chains into the giant web pulls
   * the whole reachable subgraph (every node a card, every edge an arrow).
   */
  graphFor(spec) {
    // `spec.chapter` (1..10) prunes chapter-gated arms to that chapter; applies
    // only to the forward-closure view (a conversation opened from a root),
    // where following a chapter switch's matching arm is meaningful. null/absent
    // = no filtering. Component/hub views ignore it (their node set is fixed).
    const chapter = (spec && spec.chapter != null) ? spec.chapter : null;
    // `spec.showDev` (default false) surfaces the PAGE_THRU developer paging
    // edges (cond == PAGE_THRU_COND). Hidden by default so a conversation's
    // closure stops at its END-OF-PATH markers instead of paging into the next.
    const showDev = !!(spec && spec.showDev);
    if (spec && spec.forwardFrom !== undefined) {
      return this._renderGraph(
        this.forwardClosure(spec.forwardFrom, chapter, showDev), chapter, showDev);
    }
    let nodeList;
    if (typeof spec === 'number') {
      const comp = this.components[spec];
      nodeList = comp ? comp.nodes : [];
    } else if (spec && spec.hubKey !== undefined) {
      nodeList = this.neighborhood(spec.hubKey, spec.depth || 1, showDev);
    } else {
      nodeList = [];
    }
    return this._renderGraph(nodeList, null, showDev);
  }

  /**
   * Build {nodes, edges} display payload for an explicit node list. Every node
   * becomes a full display card; edges between two in-view nodes become arrows.
   * (Out-edges to nodes NOT in the list — a cross-component / off-view target —
   * are dropped here and surfaced by the canvas as dashed out-of-view stubs.)
   */
  _renderGraph(nodeList, chapter = null, showDev = false) {
    const present = new Set(nodeList.map((n) => n.id));
    // Fused-cascade members (consumed switches / pass-throughs / spliced glue)
    // are HIDDEN when their fusing host is also in view. fusedFrom is transitive
    // (a host adopts its consumed switches' lists), so a plain union suffices; a
    // consumed switch viewed WITHOUT its fuser stays visible as its own host.
    const hidden = new Set();
    for (const n of nodeList) {
      if (!n.switchInfo || !n.switchInfo.fusedFrom) continue;
      for (const f of n.switchInfo.fusedFrom) {
        if (present.has(f.nodeId)) hidden.add(f.nodeId);
      }
    }
    const visible = nodeList.filter((n) => !hidden.has(n.id));
    const nodes = visible.map((n) => ({
      id: n.id,
      key: n.key,
      class: n.class,
      firstLine: this.firstLine(n),
      speaker: this.speakerName(n),
      badges: this.badges(n),
      shared: n.inDegree >= 2,
      // Switch nodes carry their FUSED arm structure so the renderer can title
      // the card, tint per-arm edges, and drive per-arm collapse (all flat).
      switch: n.switchInfo || null,
    }));
    const edges = [];
    const seenEdge = new Set();
    const pushEdge = (from, to, label, kind, switchArm) => {
      const sig = `${from}\x00${to}\x00${kind}`;
      if (seenEdge.has(sig)) return;
      seenEdge.add(sig);
      const edge = { from, to, label, kind };
      if (switchArm) edge.switchArm = switchArm;
      edges.push(edge);
    };
    for (const n of visible) {
      if (n.switchInfo) {
        // A switch emits its FUSED arm edges (entry order: ranges…, else last),
        // not its raw entry edges — the cascade collapses into one fan-out.
        n.switchInfo.arms.forEach((arm, ai) => {
          const t = arm.targetIds[0];
          if (!t || !present.has(t) || hidden.has(t)) return;
          // Dev-path filter: drop a PAGE_THRU developer arm unless dev paths
          // are shown (same rule outEdges applies to raw entries).
          if (!showDev && arm.entry && (arm.entry.cond >>> 0) === PAGE_THRU_COND) return;
          // Chapter filter: drop an arm whose raw entry (evaluated against its
          // owning node's siblings) doesn't survive chapter == N.
          if (chapter != null && arm.entry
            && !this.entrySurvivesChapter(arm.entry, arm.srcNode || n, chapter)) return;
          pushEdge(n.id, t, arm.edgeLabel, 'cond',
            { stateNodeId: n.id, armIndex: ai });
        });
        // Defensive: op-16 chain pushes still render (classify makes a chain
        // node win over switch, so this is normally empty).
        for (const op of n.ops) {
          if (op.op !== 0x10) continue;
          const res = this.resolveTarget(n.file, op16Key(op));
          if (res && res.node && present.has(res.node.id) && !hidden.has(res.node.id)) {
            pushEdge(n.id, res.node.id, `⛓ ${op16Key(op)}`, 'chain');
          }
        }
        continue;
      }
      for (const e of this.outEdges(n, chapter, showDev)) {
        if (!e.node || !present.has(e.node.id) || hidden.has(e.node.id)) continue;
        pushEdge(n.id, e.node.id, e.label, e.kind);
      }
    }
    const graph = { nodes, edges };
    // Audit metadata: how many structural nodes the fusion hid in THIS view.
    graph.meta = { fused: hidden.size, hiddenIds: hidden };
    return graph;
  }

  /**
   * True when an entry survives the chapter filter (chapter == N). Chapter
   * entries (cond == 0x7537) survive only when N is within [min,max]; the
   * cond==0 else survives unless a sibling chapter entry on the SAME node matches
   * N (the chapter branch was taken, so the else wouldn't run); all other
   * conditions (flags/keywords — unevaluable) always survive. `chapter` null =
   * no filtering (every entry survives). See docs feature note.
   */
  entrySurvivesChapter(entry, node, chapter) {
    if (chapter == null) return true;
    if (entry.cond === CHAPTER_STATE_ID) {
      return chapter >= entry.min && chapter <= entry.max;
    }
    if (entry.cond === 0) {
      // else/default: skipped only if a sibling chapter arm matches N.
      const chapterTaken = node.entries.some((s) => s.cond === CHAPTER_STATE_ID
        && chapter >= s.min && chapter <= s.max);
      return !chapterTaken;
    }
    return true; // non-chapter conditions are followed normally.
  }

  /**
   * Outgoing edges of a node: entry choices (kind 'cond'|'choice'|'keyword')
   * and op-0x10 chain pushes (kind 'chain'). op-21 nodes get a 'return' marker
   * with no destination. Each carries {node, label, kind, entry?}.
   *
   * `chapter` (optional, 1..10) prunes chapter-gated arms to that chapter: a
   * chapter entry whose window excludes N, and the else arm when a sibling
   * chapter arm matches N, are dropped (see entrySurvivesChapter). null/absent
   * = no filtering.
   *
   * `showDev` (default false) hides the PAGE_THRU developer paging edges
   * (cond == PAGE_THRU_COND); pass true to include them. Composes with the
   * chapter filter — both prunes apply.
   */
  outEdges(node, chapter = null, showDev = false) {
    const out = [];
    const menuMode = (node.flags & 0x0200) !== 0;
    const askMode = (node.flags & 0x0400) !== 0;
    node.entries.forEach((e, entryIdx) => {
      // Skip the developer PAGE_THRU gate unless dev paths are requested — its
      // flag is never set in play, so following it leaks the next conversation.
      if (!showDev && (e.cond >>> 0) === PAGE_THRU_COND) return;
      if (!this.entrySurvivesChapter(e, node, chapter)) return;
      const res = this.resolveTarget(node.file, e.target);
      // Edge kind: askabout topic -> 'keyword'; paged-menu player pick ->
      // 'choice'; everything else is an engine condition/else edge -> 'cond'.
      let kind = 'cond';
      if (askMode) kind = 'keyword';
      else if (menuMode) kind = 'choice';
      out.push({
        node: res ? res.node : null,
        label: this.describeEntry(e, node), kind, entryIdx,
      });
    });
    for (const op of node.ops) {
      if (op.op === 0x10) {
        const res = this.resolveTarget(node.file, op16Key(op));
        // A ⛓ marker keeps the op-16 page-turn edge visible as a chain arrow.
        out.push({ node: res ? res.node : null, label: `⛓ ${op16Key(op)}`, kind: 'chain' });
      }
    }
    return out;
  }

  /** Hub nodes (entries >= minEntries) inside the giant cyclic component. */
  hubs(minEntries = 6) {
    const giant = this.components[0];
    if (!giant) return [];
    return giant.nodes
      .filter((n) => n.entries.length >= minEntries)
      .sort((a, b) => b.entries.length - a.entries.length);
  }

  /**
   * Nodes within `depth` out/in-edge hops of a hub key (BFS over the undirected
   * graph). Keeps the UI from ever rendering the whole 5362-node component.
   */
  neighborhood(hubKey, depth = 1, showDev = false) {
    const start = this.nodeByKey(hubKey) || this.nodes.get(hubKey);
    if (!start) return [];
    const seen = new Set([start.id]);
    let frontier = [start];
    for (let d = 0; d < depth; d++) {
      const next = [];
      for (const n of frontier) {
        const neighbors = [
          ...this.outEdges(n, null, showDev).map((e) => e.node),
          ...(n.inNodes || []),
        ];
        for (const m of neighbors) {
          if (m && !seen.has(m.id)) { seen.add(m.id); next.push(m); }
        }
      }
      frontier = next;
    }
    return [...seen].map((id) => this.nodes.get(id));
  }

  /**
   * FULL forward-reachable closure from a node (BFS over out-edges, following
   * entry AND op-16 chain AND cross-file bit-31 targets inline). UNCAPPED: it
   * follows every edge — including through keyword hubs — to full reachability,
   * so a conversation that chains into the giant web pulls the entire reachable
   * subgraph. Returns [dbNode]. `startIdOrKey` is a nodeId string or a key.
   * `chapter` (optional 1..10) restricts the closure to that chapter: the
   * outEdges filter prunes non-matching chapter arms, AND every OTHER chapter's
   * arm-target block is fenced off (see _foreignChapterEntries) so the shared
   * downstream chains that bridge one chapter's block into the next don't leak
   * later-chapter content in. null = every arm followed.
   *
   * `showDev` (default false) hides the PAGE_THRU developer paging edges; the
   * fence pre-scan also honors it so a dev edge never seeds a foreign block.
   */
  forwardClosure(startIdOrKey, chapter = null, showDev = false) {
    const start = this.nodes.get(startIdOrKey) || this.nodeByKey(startIdOrKey);
    if (!start) return [];
    const blocked = chapter == null ? null
      : this._foreignChapterEntries(start, chapter, showDev);
    const seen = new Set([start.id]);
    const order = [start];
    const queue = [start];
    while (queue.length) {
      const n = queue.shift();
      for (const e of this.outEdges(n, chapter, showDev)) {
        if (!e.node || seen.has(e.node.id)) continue;
        if (blocked && blocked.has(e.node.id)) continue;
        seen.add(e.node.id);
        order.push(e.node);
        queue.push(e.node);
      }
    }
    return order.map((n) => this.nodes.get(n.id));
  }

  /**
   * The set of node ids that are a chapter switch's arm-target for some chapter
   * OTHER than `chapter`, to be fenced off when filtering. A chapter switch's
   * arms designate each chapter's OWN entry block; those blocks reconverge
   * downstream (a shared keyword-response chain bridges one chapter's block into
   * the next), so pruning the switch arm alone still leaks the sibling blocks.
   * Pre-scans the UNFILTERED forward reach so every chapter switch (not just the
   * root) is found and an owned node is fenced even when a bridge reaches it
   * first. A target that is ALSO the selected chapter's entry (a block shared by
   * this chapter) stays reachable; the start node is never fenced.
   */
  _foreignChapterEntries(start, chapter, showDev = false) {
    const reach = new Set([start.id]);
    const queue = [start];
    while (queue.length) {
      const n = queue.shift();
      for (const e of this.outEdges(n, null, showDev)) {
        if (e.node && !reach.has(e.node.id)) { reach.add(e.node.id); queue.push(e.node); }
      }
    }
    const owned = new Set();
    const foreign = new Set();
    for (const id of reach) {
      const node = this.nodes.get(id);
      for (const en of node.entries) {
        if (en.cond !== CHAPTER_STATE_ID) continue;
        const res = this.resolveTarget(node.file, en.target);
        if (!res || !res.node) continue;
        (chapter >= en.min && chapter <= en.max ? owned : foreign).add(res.node.id);
      }
    }
    for (const id of owned) foreign.delete(id);
    foreign.delete(start.id);
    return foreign;
  }

  // -- decoders -------------------------------------------------------------

  /**
   * First non-empty text line of a node's OWN body (no recursion), CLEANED for
   * preview: control bytes (tab 0x09 etc.) are stripped at the ends and collapsed
   * to a single space internally — the ⟨NN⟩ escape rendering is reserved for the
   * inspector full-body view. A `#title#` body renders as its bare title.
   */
  firstLine(node, maxLen = 40) {
    const title = this.titleOf(node);
    if (title !== null) return title.length > maxLen ? title.slice(0, maxLen) + '…' : title;
    let s = '';
    let pendingSpace = false;
    for (const b of node.textBytes) {
      if (b === 0x0a) { if (s) break; else continue; }
      if (b < 0x20) { if (s) pendingSpace = true; continue; } // collapse control bytes
      if (pendingSpace) { s += ' '; pendingSpace = false; }
      s += String.fromCharCode(b);
      if (s.length >= maxLen) { s += '…'; break; }
    }
    return s;
  }

  /**
   * If a node's body is a bare `#title#` form (a bevelled speech-bubble title,
   * docs §6), return the title text (control-cleaned); otherwise null. The title
   * is the text between the first pair of `#` delimiters on the first line.
   */
  titleOf(node) {
    let s = '';
    for (const b of node.textBytes) {
      if (b === 0x0a) break;
      if (b < 0x20) { if (s && s[s.length - 1] !== ' ') s += ' '; continue; }
      s += String.fromCharCode(b);
    }
    s = s.trim();
    if (s.length < 2 || s[0] !== '#') return null;
    const end = s.indexOf('#', 1);
    if (end <= 0) return null;
    // A pure title has nothing meaningful after the closing '#'.
    if (s.slice(end + 1).trim()) return null;
    return s.slice(1, end).trim();
  }

  /** Human speaker label for a node (KEYWORD.DAT name, sentinel, or id). */
  speakerName(node) {
    const id = node.speakerId & 0xff;
    if (id === 0) return 'narrator';
    if (id === 0xfe) return 'active-speaker';
    if (id === 0xff) return 'party-speaker';
    if (id === 0xfd) return 'npc-speaker';
    if (id >= 0xf0) return `name-slot ${id - 0xf0}`;
    const kw = this.keywords ? this.keywords.name(id) : null;
    return kw || `speaker ${id}`;
  }

  /** Short display badges for a node (mode flags + terminator/chain markers). */
  badges(node) {
    const out = [];
    const f = node.flags;
    if (f & 0x0400) out.push('askabout');
    if (f & 0x0200) out.push('menu');
    if (f & 0x0800) out.push('random');
    if (f & 0x0002) out.push('portrait');
    if (node.ops.some((o) => o.op === 21)) out.push('end');
    if (node.ops.some((o) => o.op === 0x10)) out.push('chain');
    if (this.isCipher(node)) out.push('cipher');
    return out;
  }

  /** True when a node is a wordlock cipher blob (key in the cipher range). */
  isCipher(node) {
    return node.key !== null && node.key >= CIPHER_KEY_MIN && node.key < CIPHER_KEY_MAX;
  }

  /**
   * Classify a node: 'cipher' | 'keyword-hub' | 'menu' | 'switch' | 'branch' |
   * 'chain' | 'text'. Precomputed onto node.class at build time; a 'switch' also
   * caches node.switchInfo (see detectSwitch).
   */
  classify(node) {
    if (this.isCipher(node)) return 'cipher';
    if (node.flags & 0x0400) return 'keyword-hub';
    if (node.flags & 0x0200) return 'menu';
    if (node.ops.some((o) => o.op === 0x10)) return 'chain';
    if (node.entries.some((e) => e.cond !== 0)) {
      const sw = this.detectSwitch(node);
      if (sw) { node.switchInfo = sw; return 'switch'; }
      return 'branch';
    }
    if (node.entries.length > 1) return 'menu';
    return 'text';
  }

  /**
   * Human label for one entry (condition describer). Uses the node's mode flags:
   * askabout -> KEYWORD.DAT topic label; random -> probability; else the
   * cond/min/max range against the state-name map (docs §5).
   */
  describeEntry(entry, node) {
    const f = node.flags;
    if (f & 0x0800) return `random 1/${node.nEntries}`;
    if (f & 0x0400) {
      const topic = this.keywords ? this.keywords.topic(entry.cond) : null;
      return topic ? `ask: ${topic}` : `ask topic ${entry.cond}`;
    }
    if (f & 0x0200) {
      // Paged-menu node: each entry's cond is a keyword-topic LABEL index
      // (Yes/No/Accept/West/…), NOT a gstate flag — resolve it to the button text.
      const topic = this.keywords ? this.keywords.topic(entry.cond) : null;
      return topic || `option ${entry.cond}`;
    }
    if (entry.cond === 0) {
      // 'else' is only meaningful as a DEFAULT ARM: >= 2 entries with at least
      // one conditional sibling (or paged-menu choices). A plain sequence
      // node's lone unconditional continuation gets a bare, unlabeled arrow.
      const isDefaultArm = node.entries.length >= 2
        && (node.entries.some((s) => s.cond !== 0) || (f & 0x0200) !== 0);
      return isDefaultArm ? 'else' : '';
    }
    if (entry.cond >= 56000 && entry.cond % 10 === 0) {
      return `bitmap row ${(entry.cond - 56000) / 10}`;
    }
    // topic-inhibited N (6700+N) is indexed by TOPIC id → label it with the keyword.
    if (entry.cond >= 6700 && entry.cond <= 6999) {
      const t = this._topicName(entry.cond - 6700);
      if (t) {
        if (entry.min === 1 && entry.max === 0xffff) return `topic inhibited: ${t}`;
        if (entry.min === 0 && entry.max === 0) return `topic open: ${t}`;
      }
    }
    const name = stateName(entry.cond);
    // A NAMED boolean state (a plain word like `night`/`day`, not a raw flag/
    // hex/index) reads as a natural predicate: [1..65535] -> `if night`,
    // [0..0] -> `if not night`.
    const named = /^[a-z][a-z-]*$/i.test(name) && !name.startsWith('flag');
    if (entry.min === 1 && entry.max === 0xffff) return named ? `if ${name}` : `${name} set`;
    if (entry.min === 0 && entry.max === 0) return named ? `if not ${name}` : `${name} clear`;
    if (entry.min === entry.max) return `${name} == ${entry.min}`;
    return `${name} in ${entry.min}..${entry.max}`;
  }

  /**
   * Human label for one op (op describer, docs §4). Returns a short "name arg"
   * string.
   */
  /**
   * KEYWORD.DAT label for a conversation TOPIC id, or null if it doesn't resolve
   * to a clean printable string. Used to name topic-inhibited states (which are
   * genuinely indexed by topic id — unlike the keyword-asked latch space, which
   * is reused for arbitrary flags and must NOT be topic-substituted).
   */
  _topicName(topicId) {
    const t = this.keywords && this.keywords.topic ? this.keywords.topic(topicId) : null;
    return (t && /^[\x20-\x7e]+$/.test(t) && t.trim()) ? t : null;
  }

  describeOp(op) {
    const name = OP_NAMES[op.op] || `op ${op.op}`;
    switch (op.op) {
      case 4: {
        // topic-inhibited N (6700+N) sets/clears a keyword's availability by TOPIC.
        const v = op.a1 >>> 0;
        if (v >= 6700 && v <= 6999) {
          const t = this._topicName(v - 6700);
          if (t) return op.a4 ? `inhibit topic: ${t}` : `re-enable topic: ${t}`;
        }
        return `set ${stateName(op.a1)} = ${op.a4}`;
      }
      case 6: return `layout rect (${op.a1},${op.a2},${op.a3},${op.a4})`;
      case 7: return `${EVTCOND_ACTIONS[op.a1] || `action ${op.a1}`}`;
      case 12: return op.a1 < 1000 ? `sfx ${op.a1} (phase ${op.a2})` : `music ${op.a1}`;
      case 13: return `advance time ${(((op.a2 & 0xffff) << 16) | (op.a1 & 0xffff)) >>> 0}`;
      case 14: return `set+timer ${stateName(op.a1)}`;
      case 16: return `chain -> ${op16Key(op)}`;
      case 21: return `end (result ${op.a1})`;
      default: return name;
    }
  }

  // -- switch detection (graph-readability, dialoggraph.js consumer) ---------

  /**
   * Detect a SWITCH: a branch node whose entries are mutually-exclusive
   * conditions on ONE state id. Qualifies when its entries yield >= 2 arms on the
   * SAME state id: either >= 2 range conditions with pairwise-disjoint windows,
   * or one condition plus a trailing cond==0 "else" (a boolean 'if X / else'
   * switch). askabout / paged-menu / random nodes are never switches (their
   * entries are player choices, not mutually-exclusive state ranges). Returns
   * null when it is not a switch, else:
   *   { stateId, stateName, arms:[{label, entryIdx, targetIds:[nodeId], isElse}] }
   * where entryIdx indexes node.entries (maps the arm to its out-edge) and
   * targetIds are the resolved in-graph destinations.
   */
  detectSwitch(node) {
    if (node.flags & (0x0400 | 0x0200 | 0x0800)) return null;
    const es = node.entries;
    if (es.length < 2) return null;
    let stateId = null;
    const ranges = [];      // [{entry, entryIdx}]
    let elseArm = null;     // {entry, entryIdx}
    for (let i = 0; i < es.length; i++) {
      const e = es[i];
      if (e.cond === 0) {
        // A cond==0 else is only allowed as the LAST arm.
        if (elseArm) return null;
        elseArm = { entry: e, entryIdx: i };
        continue;
      }
      if (elseArm) return null; // a condition after an else: not a clean switch
      // Bitmap-mode entries are byte-aliased, not numeric ranges — bail.
      if (e.cond >= 56000 && e.cond % 10 === 0) return null;
      if (stateId === null) stateId = e.cond;
      else if (e.cond !== stateId) return null;
      ranges.push({ entry: e, entryIdx: i });
    }
    // Need >= 2 arms total: either >= 2 range conditions, or 1 condition + else
    // (a boolean 'if X / else' switch, e.g. 'night?' / 'met Phillip?').
    if (stateId === null) return null;
    if (ranges.length + (elseArm ? 1 : 0) < 2) return null;
    // Require pairwise-disjoint windows (mutually exclusive arms).
    const sorted = ranges.slice().sort((a, b) => a.entry.min - b.entry.min);
    for (let i = 1; i < sorted.length; i++) {
      if (sorted[i].entry.min <= sorted[i - 1].entry.max) return null; // overlap
    }
    const mkArm = ({ entry, entryIdx }, isElse) => {
      const res = this.resolveTarget(node.file, entry.target);
      return {
        label: this.switchArmLabel(entry),
        entryIdx, isElse,
        entry,                    // raw entry (fusion re-labels via describeEntry)
        targetIds: res && res.node ? [res.node.id] : [],
      };
    };
    const arms = ranges.map((r) => mkArm(r, false));
    if (elseArm) arms.push(mkArm(elseArm, true));
    return { stateId, stateName: stateName(stateId), arms };
  }

  /** Short arm label for a switch edge pill ('= 1', '3..6', 'set', 'else'). */
  switchArmLabel(entry) {
    if (entry.cond === 0) return 'else';
    if (entry.min === entry.max) return `= ${entry.min}`;
    if (entry.min === 1 && entry.max === 0xffff) return 'set';
    if (entry.min === 0 && entry.max === 0) return 'clear';
    return `${entry.min}..${entry.max}`;
  }

  // -- switch fusion + arm splicing ------------------------------------------

  /**
   * True for a TRULY-EMPTY pass-through node: no body text (after control-byte
   * strip), no significant ops (op-0 nop and op-6 style-rect are inert), exactly
   * one unconditional entry, and no player-choice mode flags. These are the
   * structural glue nodes the authored if/else-if cascades chain through; they
   * are safe to splice out of the RENDERED graph when they also have in-degree 1.
   */
  _isEmptyPassthru(node) {
    if (node.flags & (0x0400 | 0x0200 | 0x0800)) return false;
    if (node.entries.length !== 1 || node.entries[0].cond !== 0) return false;
    if (node.ops.some((o) => o.op !== 0 && o.op !== 6)) return false;
    for (const b of node.textBytes) if (b >= 0x21) return false;
    return true;
  }

  /**
   * Follow a chain of empty pass-through nodes (each in-degree 1) from a node
   * id. Stops at the first node that is not an empty in-degree-1 pass-through,
   * or whose target dangles / cycles. Returns {final, passed} where `final` is
   * the landing node id and `passed` the consumed pass-through ids (in order).
   */
  _walkEmpties(startId) {
    const passed = [];
    const seen = new Set([startId]);
    let cur = startId;
    for (;;) {
      const n = this.nodes.get(cur);
      if (!n || !this._isEmptyPassthru(n) || n.inDegree !== 1) {
        return { final: cur, passed };
      }
      const res = this.resolveTarget(n.file, n.entries[0].target);
      if (!res || !res.node || seen.has(res.node.id)) return { final: cur, passed };
      passed.push(cur);
      seen.add(res.node.id);
      cur = res.node.id;
    }
  }

  /**
   * SWITCH FUSION over the whole graph (build-time; needs in-degrees). The
   * authored data often encodes one logical switch as an if/else-if CASCADE:
   * S1 tests state X, its else falls (directly or through empty pass-throughs)
   * into S2 testing the SAME X, and so on. Rendered literally that is a diagonal
   * chain with phantom empty cards. This pass rewrites every switch node's
   * switchInfo into its FUSED form:
   *   - non-else arms keep their original cond windows (labels preserved) and
   *     are SPLICED: empty in-degree-1 pass-throughs between the arm and its
   *     first content node are consumed (role 'spliced');
   *   - the else arm is followed: if it lands on another switch on the same
   *     state id with in-degree 1, that switch's (already fused) arms are merged
   *     in (roles 'passthru' for swallowed glue, 'switch' for the consumed
   *     switch) and its own fusedFrom adopted; otherwise the else arm is kept
   *     (spliced) as the terminal default arm.
   * Consumed nodes are recorded in switchInfo.fusedFrom = [{nodeId, role}] and
   * hidden per-view by _renderGraph ONLY when their host is in view — a
   * consumed switch still renders as its own host in a view without its fuser.
   * Never fuses through nodes with body text, significant ops, or extra
   * parents (those render honestly). Terminates: consumption follows in-degree-1
   * chains with a cycle guard, and each switch is fused at most once (memoized).
   */
  _fuseSwitches() {
    const done = new Set();
    const inProgress = new Set();
    const fuse = (node) => {
      if (done.has(node.id) || !node.switchInfo) return;
      inProgress.add(node.id);
      const base = node.switchInfo;
      const arms = [];
      const fusedFrom = [];
      // Splice one arm: walk empties from its target; consumed glue is recorded.
      const spliceArm = (arm, owner) => {
        const t = arm.targetIds[0];
        let targetIds = arm.targetIds;
        if (t) {
          const w = this._walkEmpties(t);
          if (w.passed.length) {
            for (const p of w.passed) fusedFrom.push({ nodeId: p, role: 'spliced' });
            targetIds = [w.final];
          }
        }
        arms.push({
          label: arm.label, isElse: arm.isElse,
          edgeLabel: this.describeEntry(arm.entry, owner),
          srcNodeId: owner.id, targetIds, entryIdx: 0,
          // Raw entry + its owning node kept so a chapter filter can re-evaluate
          // arm survival at render time (else-arm rule needs the owner's siblings).
          entry: arm.entry, srcNode: owner,
        });
      };
      for (const a of base.arms) if (!a.isElse) spliceArm(a, node);
      const elseArm = base.arms.find((a) => a.isElse);
      if (elseArm) {
        const t = elseArm.targetIds[0];
        const w = t ? this._walkEmpties(t) : { final: null, passed: [] };
        const next = w.final ? this.nodes.get(w.final) : null;
        const fusable = next && next.switchInfo
          && next.id !== node.id && !inProgress.has(next.id)
          && next.switchInfo.stateId === base.stateId
          && next.inDegree === 1;
        if (fusable) {
          for (const p of w.passed) fusedFrom.push({ nodeId: p, role: 'passthru' });
          fusedFrom.push({ nodeId: next.id, role: 'switch' });
          fuse(next);   // ensure next's own fused form (memoized)
          for (const na of next.switchInfo.arms) arms.push({ ...na });
          for (const c of next.switchInfo.fusedFrom || []) fusedFrom.push(c);
        } else {
          spliceArm(elseArm, node);
        }
      }
      arms.forEach((a, i) => { a.entryIdx = i; });
      node.switchInfo = { stateId: base.stateId, stateName: base.stateName, arms, fusedFrom };
      inProgress.delete(node.id);
      done.add(node.id);
    };
    for (const n of this.nodes.values()) if (n.switchInfo) fuse(n);
  }

  // -- search ---------------------------------------------------------------

  /** Case-insensitive body-text search; returns [{node, line}] hits. */
  search(text, limit = 200) {
    const q = String(text).toLowerCase();
    if (!q) return [];
    const hits = [];
    for (const node of this.nodes.values()) {
      if (!node.textBytes.length) continue;
      const body = node._text || (node._text = decodeText(node.textBytes));
      if (body.toLowerCase().includes(q)) {
        hits.push({ node, line: this.firstLine(node) });
        if (hits.length >= limit) break;
      }
    }
    return hits;
  }
}

/** Decode a body-text byte array into a display string (\n kept). */
function decodeText(bytes) {
  let s = '';
  for (const b of bytes) {
    if (b === 0x0a) s += '\n';
    else if (b < 0x20) s += ' ';
    else s += String.fromCharCode(b);
  }
  return s;
}

// ---- KEYWORD.DAT decoder -----------------------------------------------------

/**
 * Parse KEYWORD.DAT. Two index regions over one string pool:
 *  - topic labels: offsets[0..N-1], looked up at (topicId-1)*2+2;
 *  - speaker/proper names: looked up at (id+0x124)*2+2 for id >= 7.
 * String pointers are raw offsets relative to the resource base `data`.
 */
export function parseKeywords(bytes) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  if (view.byteLength < 4) return null;
  const outerSize = view.getUint16(0, true);
  // inner blob = bytes[2 .. 2+outerSize]; index offsets read from inner, strings
  // resolved at bytes (data) + rawOffset.
  const innerBase = 2;
  const N = view.getUint16(innerBase, true);
  const readStr = (rawOff) => {
    let s = '';
    for (let i = rawOff; i < view.byteLength; i++) {
      const c = view.getUint8(i);
      if (c === 0) break;
      s += String.fromCharCode(c);
    }
    return s;
  };
  return {
    outerSize, N,
    /** Askabout topic label for a 1-based topic id, or null. */
    topic(topicId) {
      if (topicId < 1 || topicId > N) return null;
      const idxOff = innerBase + (topicId - 1) * 2 + 2;
      if (idxOff + 2 > view.byteLength) return null;
      return readStr(view.getUint16(idxOff, true));
    },
    /** Speaker/proper name for a keyword id (>= 7), or null. */
    name(id) {
      if (id < 7) return null;
      const idxOff = innerBase + (id + 0x124) * 2 + 2;
      if (idxOff + 2 > view.byteLength) return null;
      return readStr(view.getUint16(idxOff, true));
    },
  };
}

// ---- roots collection --------------------------------------------------------

/**
 * Collect external roots from world data. Returns [{key, kind, detail}] where
 * key is a directory key and kind is 'object'|'hotspot'|'cipher'|'engine'.
 * gameData supplies OBJFIXED/STARTUP interact-message ids, DEF dialog payloads
 * and cipher ids (already parsed there — reused, not re-implemented).
 */
function collectRoots(gameData) {
  const roots = [];
  const push = (key, kind, detail) => {
    const k = (key & KEY_MASK) >>> 0;
    if (k !== 0) roots.push({ key: k, kind, detail });
  };

  // Engine-hardcoded keys.
  for (const k of ENGINE_KEYS) push(k, 'engine', 'dialog_play_record literal');

  if (!gameData) return roots;

  // Object/hotspot interact-message ids + cipher ids from every zone's state
  // records (OBJFIXED.DAT + STARTUP.GAM), parsed by gamedata.js.
  const seenCipher = new Set();
  for (let zone = 1; zone <= 15; zone++) {
    for (const r of gameData.zoneRecords(zone)) {
      const mid = fieldVal(r, 'msg.messageId');
      if (mid) push(mid, 'object', `${r.source} zone ${zone} @${hex(r.offset)}`);
      const cipher = fieldVal(r, 'lock.cipherPuzzleId');
      if (cipher && !seenCipher.has(cipher)) {
        seenCipher.add(cipher);
        push(CIPHER_KEY_BASE + cipher - 1, 'cipher', `wordlock cipher ${cipher}`);
      }
    }
  }

  // DEF payload dialog keys, across every kind + index seen in tile hotspots.
  for (const { kind, names } of DEF_DIALOG_FIELDS) {
    for (let idx = 0; idx < 512; idx++) {
      const def = gameData.defRecordDecoded ? gameData.defRecordDecoded(kind, idx) : null;
      if (!def || !def.bytes) { if (idx > 0 && !def) break; continue; }
      for (const nm of names) {
        const key = defFieldVal(def, nm);
        if (key) push(key, 'hotspot', `${def.file} #${idx} ${nm}`);
      }
    }
  }
  return roots;
}

/** A decoded container-record field value by name, or 0. */
function fieldVal(record, name) {
  if (!record || !record.fields) return 0;
  const f = record.fields.find((x) => x.name === name);
  return f ? f.value : 0;
}

/** A decoded DEF field value by name, or 0. */
function defFieldVal(def, name) {
  const f = (def.fields || []).find((x) => x.name === name);
  return f ? f.value : 0;
}

// ---- builder -----------------------------------------------------------------

/**
 * Parse every DIAL_Z*.DDX in the archive into a DialogDb: discover nodes by
 * (file, offset), build the graph, compute components/roots, and wire the
 * decoders. `gameData` (optional) supplies external roots.
 * @param {import('./rmf.js').Archive} archive
 * @param {import('./gamedata.js').GameData|null} gameData
 * @returns {DialogDb}
 */
export function loadDialogDb(archive, gameData) {
  const db = new DialogDb();

  // 1. Parse directories, discover nodes by BFS over in-file offset targets and
  //    op-0x10 pushes, seeded from directory records + all external roots.
  const externalKeys = collectRoots(gameData);
  db._roots = externalKeys;

  // Group external keys by file so a bit-31 key root can seed its own file.
  const rootsByFile = new Map();
  for (const r of externalKeys) {
    const fn = keyToFile(r.key);
    if (!rootsByFile.has(fn)) rootsByFile.set(fn, []);
    rootsByFile.get(fn).push(r);
  }

  for (let fn = 0; fn <= 31; fn++) {
    const bytes = archive.getResource(dialFileName(fn));
    if (!bytes || bytes.byteLength < 2) continue;
    const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
    const count = view.getUint16(0, true);
    const dir = new Map();       // key -> offset
    const offToKey = new Map();  // offset -> key
    for (let i = 0; i < count; i++) {
      const o = 2 + i * 8;
      if (o + 8 > view.byteLength) break;
      const key = view.getUint32(o, true);
      const off = view.getUint32(o + 4, true);
      dir.set(key, off);
      if (!offToKey.has(off)) offToKey.set(off, key);
    }
    db._files.set(fn, { view, dir });

    // BFS discovery seeded from directory offsets + external-root offsets.
    const seen = new Set();
    const queue = [...dir.values()];
    for (const r of (rootsByFile.get(fn) || [])) {
      const off = dir.get(r.key);
      if (off !== undefined) queue.push(off);
    }
    while (queue.length) {
      const off = queue.pop();
      if (seen.has(off)) continue;
      const rec = parseRecord(view, off);
      if (!rec) continue;
      seen.add(off);
      const id = nodeId(fn, off);
      const key = offToKey.has(off) ? offToKey.get(off) : null;
      const node = Object.assign(rec, { id, file: fn, offset: off, key });
      db.nodes.set(id, node);
      if (key !== null && !db.byKey.has(key)) db.byKey.set(key, node);
      for (const e of rec.entries) {
        const m = (e.target & KEY_MASK) >>> 0;
        if (m !== 0 && (e.target & KEY_FLAG) === 0) queue.push(m);
      }
      for (const op of rec.ops) {
        if (op.op === 0x10) {
          const k = op16Key(op);
          const m = (k & KEY_MASK) >>> 0;
          if (m !== 0 && (k & KEY_FLAG) === 0) queue.push(m);
        }
      }
    }
  }

  // 2. Edges + degrees + adjacency for components / neighborhoods.
  let danglingCount = 0;
  const kindCounts = { cond: 0, choice: 0, keyword: 0, chain: 0 };
  for (const node of db.nodes.values()) {
    node.inDegree = 0;
    node.inNodes = [];
    node.class = db.classify(node);
  }
  for (const node of db.nodes.values()) {
    for (const e of node.entries) {
      const m = (e.target & KEY_MASK) >>> 0;
      if (m === 0) continue;
      const res = db.resolveTarget(node.file, e.target);
      if (!res) { danglingCount++; db._danglingKeys.push({ from: node.id, raw: e.target }); }
    }
    for (const op of node.ops) {
      if (op.op === 0x10) {
        const m = (op16Key(op) & KEY_MASK) >>> 0;
        if (m === 0) continue;
        const res = db.resolveTarget(node.file, op16Key(op));
        if (!res) { danglingCount++; db._danglingKeys.push({ from: node.id, raw: op16Key(op) }); }
      }
    }
  }

  // Directed adjacency + undirected sets for WCC; also fill inNodes/inDegree.
  const undirected = new Map(); // id -> Set(id)
  const link = (a, b) => {
    if (!undirected.has(a)) undirected.set(a, new Set());
    if (!undirected.has(b)) undirected.set(b, new Set());
    undirected.get(a).add(b);
    undirected.get(b).add(a);
  };
  let resolvableEdges = 0;
  for (const node of db.nodes.values()) {
    // Build the topology (degrees / adjacency / WCC / census) over ALL edges,
    // dev PAGE_THRU included — the toggle only prunes per-VIEW rendering and
    // closures, never the underlying graph structure.
    for (const e of db.outEdges(node, null, true)) {
      if (!e.node) continue;
      resolvableEdges++;
      link(node.id, e.node.id);
      e.node.inDegree++;
      e.node.inNodes.push(node);
    }
  }
  db._resolvableEdges = resolvableEdges;

  // Switch fusion: collapse authored if/else-if cascades into single logical
  // switches (needs in-degrees, which the loop above just filled). Rewrites
  // node.switchInfo only — the raw graph (outEdges/components/closures) is
  // untouched; hiding happens per-view in _renderGraph.
  db._fuseSwitches();

  // 3. Weakly-connected components (BFS), sorted largest first.
  const compOf = db._compOf;
  const rawComps = [];
  for (const node of db.nodes.values()) {
    if (compOf.has(node.id)) continue;
    const members = [];
    const stack = [node.id];
    compOf.set(node.id, rawComps.length);
    while (stack.length) {
      const cur = stack.pop();
      members.push(db.nodes.get(cur));
      for (const nb of (undirected.get(cur) || [])) {
        if (!compOf.has(nb)) { compOf.set(nb, rawComps.length); stack.push(nb); }
      }
    }
    rawComps.push(members);
  }
  rawComps.sort((a, b) => b.length - a.length);

  // Re-index compOf after the sort, build component objects with roots + cycles.
  compOf.clear();
  const rootByKey = new Map();
  for (const r of externalKeys) {
    if (!rootByKey.has(r.key)) rootByKey.set(r.key, r);
  }
  let cyclicCount = 0;
  db.components = rawComps.map((members, ci) => {
    for (const m of members) compOf.set(m.id, ci);
    const roots = [];
    for (const m of members) {
      if (m.inDegree === 0 || (m.key !== null && rootByKey.has(m.key))) {
        const prov = m.key !== null && rootByKey.has(m.key)
          ? rootByKey.get(m.key)
          : { key: m.key, kind: 'root', detail: 'in-degree 0' };
        roots.push({ node: m, ...prov });
      }
    }
    const cyclic = componentHasCycle(members, db);
    if (cyclic) cyclicCount++;
    return {
      id: ci, size: members.length, nodes: members, roots, cyclic,
    };
  });

  // 4. KEYWORD.DAT.
  const kwBytes = archive.getResource('KEYWORD.DAT');
  db.keywords = kwBytes ? parseKeywords(kwBytes) : null;

  // 5. Census stats.
  const single = db.components.filter((c) => c.size === 1).length;
  // Non-empty partitions only: an empty DIAL_Z*.DDX is a 2-byte count=0 stub
  // that yields no nodes (Z09/Z25/Z26/Z28).
  const nonEmptyFiles = new Set([...db.nodes.values()].map((n) => n.file)).size;
  db.stats = {
    files: nonEmptyFiles,
    nodes: db.nodes.size,
    directoryKeys: db.byKey.size,
    resolvableEdges,
    dangling: danglingCount,
    duplicateKeys: 0,
    components: db.components.length,
    singleNode: single,
    giant: db.components.length ? db.components[0].size : 0,
    cyclic: cyclicCount,
    roots: externalKeys.length,
  };
  return db;
}

/** Directed-cycle test over one component's members (DFS with on-stack set). */
function componentHasCycle(members, db) {
  const ids = new Set(members.map((m) => m.id));
  const color = new Map(); // id -> 0 white,1 gray,2 black
  const outIds = (node) => {
    const out = [];
    // Cycle test runs over the full build-time topology (dev edges included).
    for (const e of db.outEdges(node, null, true)) {
      if (e.node && ids.has(e.node.id)) out.push(e.node.id);
    }
    return out;
  };
  for (const start of members) {
    if (color.get(start.id)) continue;
    const stack = [{ id: start.id, it: outIds(start), i: 0 }];
    color.set(start.id, 1);
    while (stack.length) {
      const top = stack[stack.length - 1];
      if (top.i < top.it.length) {
        const v = top.it[top.i++];
        const c = color.get(v) || 0;
        if (c === 0) {
          color.set(v, 1);
          stack.push({ id: v, it: outIds(db.nodes.get(v)), i: 0 });
        } else if (c === 1) {
          return true; // back edge -> cycle
        }
      } else {
        color.set(top.id, 2);
        stack.pop();
      }
    }
  }
  return false;
}
