#ifndef BAK_GLOBALS_H
#define BAK_GLOBALS_H
#include "structs.h"
#include "SRC/WORLD/ACTOR/ACTOR.H"

extern unsigned short g_wRandIdxJ;
extern unsigned short g_wRandIdxI;
extern unsigned short g_wRandLastVal;
extern unsigned short g_wRandTable[56];
extern unsigned long g_nVec3DistResult;
extern PolyRasterState g_polyRasterState;
extern unsigned char g_bCutsceneEscPressed;
extern short g_nPolygonTextureMode;
extern unsigned short g_nWorldRenderJitter;
extern char *g_pszCombatModalTitle;
extern BakFile *g_pSfxArchiveStream;
extern unsigned int _ovrbuffer;
extern unsigned char far *g_pMainScratchBuf;
extern char g_szVersionString[13];
extern unsigned short g_wSkyColorR;
extern unsigned short g_wSkyColorG;
extern unsigned short g_wSkyColorB;
extern ImageRecord **g_pMapIconsTable;
extern unsigned char g_abActorAnimTemplateDefault[10];
extern unsigned char g_abActorAnimTemplateRanged[10];
extern short g_cursor_hidden;
extern short g_cursor_prev_shape;
extern ImageRecord **g_cursor_state;
extern unsigned char far *g_pPalQueuedForFlip;
extern short g_nCursorX;
extern short g_nCursorY;
extern unsigned short g_nCursorStateSaved;
extern unsigned char far *g_pSavedCursorBuf1;
extern unsigned char far *g_pSavedCursorBuf2;
extern unsigned char far *g_pPalLoadedBuf;
extern unsigned char far *g_pPalAltA;
extern unsigned char far *g_pPalAltB;
extern unsigned char far *g_pPalBlendScratch;
extern unsigned short g_nPalBlendMode;
extern unsigned char far *g_pPalLastInstalled;
extern char g_rgbDayNightCycle_4f4[15];
extern int g_nPaletteBlendFactorCached;
extern Vec3Short g_aActorBoxCornerOffsets[8];
extern unsigned short g_awBoxBorderChars[9];
extern int g_nEmsInit;
extern int g_nEmsResourcesEnabled;
extern unsigned short g_wEmmPagesFree;
extern char g_szVmcodeOvl[11];
extern int g_nDialogChapterId;
extern unsigned long g_dwDialogInputCooldown;
extern unsigned char g_abTextSpeedScale[3];
extern int g_nTabWidth;
extern DialogStyleDescriptor g_dialog_style_table[7];
extern unsigned short g_bDialogWorldAnchorValid;
extern unsigned char g_dialog_running;
extern unsigned short g_bCombatGridTerrainFeaturesEnabled;
extern unsigned short g_bCombatGridLinesEnabled;
extern unsigned short g_bShowActorRosterIndex;
extern unsigned short g_bStormAmplify;
extern unsigned short **g_pTerrainBackupGrid;
extern unsigned short g_awQuarrelKindItemIdTable[8];
extern unsigned short g_quarrel_kind_field19_table[8];
extern unsigned char __dat_1466[10];

extern unsigned short g_full_redraw_needed;
extern short g_nMapReloadPending;
extern unsigned char *g_pColorRemap;
extern EnginePrefs *g_engine_prefs;
extern int g_nMenuReentering;
extern unsigned short g_wSaveSlotDirValid;
extern unsigned short g_wSaveFileValid;
extern unsigned short g_wMenuCursorPreset;
extern char g_szHealthStamina[15];
extern char g_szRations[8];
extern char g_szEncampOfSep[6];
extern unsigned short g_wZoneFlags;
extern char g_szZoneRefFilenameTmpl[11];
extern GraphicsContext g_graphics_context;
extern unsigned short g_wScreen_width;
extern unsigned short g_wScreen_height;
extern unsigned short g_pRow_offset_lut[200];
extern GraphicsContextRender g_graphics_context_render;
extern GfxDefaultFn far *g_gfx_default_fptr;
extern VideoDriverImports g_video_driver_imports;
extern char s_chunk_tag_FNT[5];
extern char s_open_mode_r[2];
extern unsigned char g_abIntensityCurve[64];
extern unsigned short g_nSfxResourceId;
extern unsigned char far *g_pSsmChunkBuf;
extern AudioListNode far *g_pActiveAudioListHead;
extern unsigned short g_bAudioTimerInstalled;
extern unsigned short g_nSfxSampleSlot;
extern unsigned short g_nSfxWorkSlot;
extern SfxLoopPri *g_pSfxLoopPriorityTable;
extern void far *g_pSfxDriver;
extern void far *g_pMusicDriver;
extern unsigned short g_nAudioBufLastError;
extern unsigned char g_bAudioLooseTag;
extern short g_nAudioFilterMode;
extern MusicChunkHeader far *g_pMusicChunkBuf;
extern BakFile *g_music_archive;
extern int g_music_archive_owned;
extern unsigned short g_bMusicDriverInstalled;
extern unsigned short g_nAudioStreamCodec;
extern void *_realcvt;
extern void *__ScanTodVector;
extern void *__scanrslt;
extern void *__scanpop;

extern short g_game_mode;
extern WorldEntity *g_world_camera;
extern ViewContext *g_world_widget;
extern unsigned char g_bZoneSkyColor;
extern unsigned char g_bZoneGroundColor;
extern void *g_pZoneGridData;
extern short g_nZoneRenderTableCount;
extern char g_szZoneMapFilename[13];
extern unsigned short g_wCurrentSaveSlotKey;
extern unsigned short g_wCurrentSaveFileKey;
extern int g_wBookmarkFmapX;
extern int g_wBookmarkFmapY;
extern unsigned short g_wBookmarkCompassIcon;
extern char g_szSaveSlotDirName_51cc[13];
extern unsigned char g_abSaveFileHeader[90];
extern unsigned short g_wExploreCameraYawSaved;
extern long g_lWorldZMin;
extern long g_lWorldZMax;
extern long g_lWorldZStep;
extern long g_lExploreCameraZSaved;
extern MenuPage *g_pReqMapPage;
extern CombatActor *g_current_actor;
extern CombatActor *g_picked_actor;
extern unsigned short g_acting_actor_speed;
extern int g_grid_tile_size;
extern short g_cursor_tile_x;
extern short g_cursor_tile_y;
extern unsigned short g_wInCombatMode;
extern MenuPage *g_combat_menu;
extern MenuPage *g_shoot_menu;
extern unsigned short g_combat_menu_selected_item;
extern unsigned short g_combat_menu_current_page;
extern short g_nCurrentQuarrelKindIdx;
extern unsigned short g_combat_cancelled;
extern unsigned short g_combat_music_handle;
extern CombatActor *g_acting_actor;
extern unsigned short g_traps_loaded_flag;
extern unsigned short g_encounter_id;
extern CombatActor *g_pCombatActiveActors;
extern AnimSlot *g_pCombatActiveAnimPool;
extern int g_nCombatActiveCount;
extern CombatActor *g_pCombatOtherActors;
extern AnimSlot *g_pCombatOtherAnimPool;
extern int g_nCombatOtherCount;
extern ImageRecord **g_combat_sprites;
extern ImageRecord **g_parch_bmx;
extern ImageRecord **g_combat_render_table_prev;
extern char g_speaker_kinds[6];
extern char g_speaker_names[6][32];
extern short g_nDialogAnchorX;
extern short g_nDialogAnchorY;
extern unsigned short g_wTimerTickRegistrySlot;
extern short g_nWorldViewYawNormal;
extern short g_nWorldViewYawChapter;
extern short g_nWorldViewFovNormal;
extern unsigned char g_bssgap_4c53;
extern unsigned char g_nWorldViewFovChapter;
extern unsigned char g_bssgap_4c34[2];
extern GridCombatant *g_combatant_table;
extern short g_combatant_count;
extern CombatTile g_combat_tile_grid[8][13];
extern int g_nCombatTerrainWallColor;
extern unsigned char g_combat_move_map[8][13];
extern CursorState g_cursor_prev_x[2];
extern unsigned char far *g_pActiveCursorBuf;
extern unsigned char far *g_pCursorScratchBuf1;
extern unsigned char far *g_pCursorScratchBuf2;
extern unsigned char g_bssgap_4863[3];
extern GameState g_gameState;
extern unsigned short g_bPaletteCycleEbActive;
extern unsigned short g_wVgaScratchPageBase;
extern unsigned short g_wGameFontSlot;
extern unsigned short *g_pSkyPanoAssetTable;
extern WorldEntity *g_render_camera_scratch;
extern ViewContext *g_active_window;
extern unsigned short g_nChapterAtLoopExit;

extern unsigned short g_wGfxBlitDstPage;

extern void(far *g_pfn_blit_stretched)(void);

#endif
