#ifndef BAK_GLOBALS_H
#define BAK_GLOBALS_H
#include "structs.h"
#include "SRC/WORLD/ACTOR/ACTOR.H"

extern char g_cBusyCursorShown;
extern unsigned short g_wRandIdxJ;
extern unsigned short g_wRandIdxI;
extern unsigned short g_wRandLastVal;
extern unsigned short g_wRandTable[56];
extern unsigned char g_abFontColorRemap[5];
extern unsigned char g_saved_text_fg_color;
extern unsigned long g_nVec3DistResult;
extern PolyRasterState g_polyRasterState;
extern unsigned char g_bCutsceneEscPressed;
extern short g_nPolygonTextureMode;
extern unsigned short g_nWorldRenderJitter;
extern char *g_pszCombatModalTitle;
extern BakFile *g_pSfxArchiveStream;
extern unsigned int _ovrbuffer;
extern unsigned char far *g_pMainScratchBuf;
extern char g_szVersionString[13];
extern unsigned short g_wSkyColorR;
extern unsigned short g_wSkyColorG;
extern unsigned short g_wSkyColorB;
extern ImageRecord **g_pMapIconsTable;
extern unsigned char g_abActorAnimTemplateDefault[10];
extern unsigned char g_abActorAnimTemplateRanged[10];
extern short g_cursor_hidden;
extern short g_cursor_prev_shape;
extern ImageRecord **g_cursor_state;
extern unsigned char far *g_pPalQueuedForFlip;
extern short g_nCursorX;
extern short g_nCursorY;
extern unsigned short g_nCursorStateSaved;
extern unsigned char far *g_pSavedCursorBuf1;
extern unsigned char far *g_pSavedCursorBuf2;
extern unsigned char far *g_pPalLoadedBuf;
extern unsigned char far *g_pPalAltA;
extern unsigned char far *g_pPalAltB;
extern unsigned char far *g_pPalBlendScratch;
extern unsigned short g_nPalBlendMode;
extern unsigned char far *g_pPalLastInstalled;
extern char g_rgbDayNightCycle_4f4[15];
extern int g_nPaletteBlendFactorCached;
extern VfxRec *g_pVfxSparkleScratch;
extern VfxRec *g_pVfxParticlePool;
extern Vec3Short g_aActorBoxCornerOffsets[8];
extern short g_nVfxTickCountdown;
extern unsigned short g_awBoxBorderChars[9];
extern int g_nEmsInit;
extern int g_nEmsResourcesEnabled;
extern unsigned short g_wEmmPagesFree;
extern char g_szVmcodeOvl[11];
extern unsigned short g_wLastTempWriteRecordKind;
extern char g_abChapterEventSlot[9];
extern BakFile *g_pTempGamFp;
extern char g_abSleepStatDelta[6];
extern char g_abRegenPerChar[6];
extern int g_nDialogChapterId;
extern unsigned long g_dwDialogInputCooldown;
extern unsigned char g_abTextSpeedScale[3];
extern int g_nTabWidth;
extern DialogStyleDescriptor g_dialog_style_table[7];
extern unsigned short g_bDialogWorldAnchorValid;
extern unsigned char g_dialog_running;
extern TownScene *g_pCurrentTownScene;
extern MenuPage *g_pTownMenuPage;
extern short g_nTownSceneAnimHandle;
extern unsigned short g_dialog_in_scene;
extern unsigned short g_inventory_screen_mode;
extern unsigned char g_bIsRestEncounter;
extern Actor far *g_other_inventory_actor;
extern Actor far *g_pDroppedItemActor;
extern MenuPage *g_pInventoryMenuPage;
extern ItemSlot far *g_pStackHeadroomSlot;
extern ImageRecord **g_pInvSpriteLoAssetTable;
extern ImageRecord **g_pInvSpriteHiAssetTable;
extern ImageRecord **g_pInvLockAssetTable;
extern ImageRecord **g_pInvMiscAssetTable;
extern unsigned char far *g_pCursorSaveBufActive;
extern unsigned char far *g_pCursorSaveBufA;
extern unsigned char far *g_pCursorSaveBufB;
extern unsigned long g_dwDblClickDeadline;
extern unsigned short g_wCombatSpinnerYaw;
extern unsigned short g_bCombatGridTerrainFeaturesEnabled;
extern unsigned short g_bCombatGridLinesEnabled;
extern unsigned short g_bShowActorRosterIndex;
extern unsigned short g_bStormAmplify;
extern unsigned short **g_pTerrainBackupGrid;
extern unsigned short g_awQuarrelKindItemIdTable[8];
extern unsigned short g_quarrel_kind_field19_table[8];
extern short g_anStatCheckThreshold[9];
extern unsigned short g_ai_flee_threshold_table[10];
extern unsigned char __dat_1466[10];
extern unsigned short g_nSpellSymbolAnimFrame;

extern MenuPage *g_pReqMainPage;
extern short g_nSceneReloadPending;
extern short g_nHotspotActivateRequest;
extern unsigned short g_full_redraw_needed;
extern short g_nMapReloadPending;
extern unsigned char *g_pColorRemap;
extern EnginePrefs *g_engine_prefs;
extern int g_nMenuReentering;
extern unsigned short g_wSaveSlotDirValid;
extern unsigned short g_wSaveFileValid;
extern unsigned short g_wMenuCursorPreset;
extern char g_szHealthStamina[15];
extern char g_szRations[8];
extern char g_szEncampOfSep[6];
extern unsigned char g_nOpenZoneTileCount;
extern char g_szZoneWldFilename[12];
extern unsigned short g_wZoneFlags;
extern char g_szZoneRefFilenameTmpl[11];
extern unsigned short g_nHotspotCount;
extern unsigned short g_wHotspotIterIdx;
extern unsigned short g_wHotspotMatchIdx;
extern unsigned short g_wHotspotEventEnabled;
extern unsigned short g_bZoneEntryInProgress;
extern unsigned short g_wHotspotIterCursor;
extern char g_monst_filename_buf[12];
extern char g_aDefFileNames[12][13];
extern short g_aDefRecordSizes[12];
extern unsigned short g_nHitTestEntryCount;
extern unsigned short g_nHitTestWriteSlot;
extern GraphicsContext g_graphics_context;
extern unsigned short g_wScreen_width;
extern unsigned short g_wScreen_height;
extern unsigned short g_pRow_offset_lut[200];
extern GraphicsContextRender g_graphics_context_render;
extern RendererVtable g_renderer_vtable;
extern GfxDefaultFn far *g_gfx_default_fptr;
extern VideoDriverImports g_video_driver_imports;
extern char s_chunk_tag_FNT[5];
extern char s_open_mode_r[2];
extern unsigned char huge *g_pCodecScratchFp;
extern CodecVtable g_codec_vtable[4];
extern unsigned char g_abLowBitMaskByWidth[9];
extern unsigned char g_abIntensityCurve[64];
extern unsigned short g_nSfxResourceId;
extern unsigned char far *g_pSsmChunkBuf;
extern AudioListNode far *g_pActiveAudioListHead;
extern unsigned short g_bAudioTimerInstalled;
extern unsigned short g_nSfxSampleSlot;
extern unsigned short g_nSfxWorkSlot;
extern SfxLoopPri *g_pSfxLoopPriorityTable;
extern void far *g_pSfxDriver;
extern void far *g_pMusicDriver;
extern unsigned short g_nAudioBufLastError;
extern unsigned char g_bAudioLooseTag;
extern short g_nAudioFilterMode;
extern MusicChunkHeader far *g_pMusicChunkBuf;
extern BakFile *g_music_archive;
extern int g_music_archive_owned;
extern unsigned short g_bMusicDriverInstalled;
extern unsigned short g_nAudioStreamCodec;
extern void *_realcvt;
extern void *__ScanTodVector;
extern void *__scanrslt;
extern void *__scanpop;

extern AudioTrackHandle far *g_apSfxSlotPool[7];
extern StreamDesc *g_pCurStreamDesc;
extern unsigned char *g_pCurStreamRingBuf;
extern unsigned char g_bCurStreamCodecId;
extern BakFile *g_pCurStreamFp;
extern unsigned char huge *g_pStreamReadDst;
extern unsigned char huge *g_pCurCodecScratch;
extern StreamDesc *g_apStreamSlots[100];
extern int g_nStreamBytesWritten;
extern unsigned short g_wCodecBytesRemaining;
extern unsigned char g_bCurStreamOpMode;
extern unsigned char g_bCurStreamDescFlags;
extern char huge *g_pCurStreamSrcCursor;
extern unsigned char g_codecRawTransitBuf[50];
extern unsigned char g_bssgap_5de5;
extern IffResReader g_chunkSeekSaveIffReader;
extern IffResReader g_iff_reader_pool[4];
extern WorldHotspot *g_pWorldHitTestTable;
extern long g_anEntityKindRenderDist[43];
extern ZoneHotspot g_aZoneHotspots[10];
extern unsigned short g_awHotspotPendingFlags[10];
extern short g_game_mode;
extern WorldEntity *g_world_camera;
extern ViewContext *g_world_widget;
extern unsigned char g_bZoneSkyColor;
extern unsigned char g_bZoneGroundColor;
extern void *g_pZoneGridData;
extern short g_nZoneRenderTableCount;
extern char g_szZoneMapFilename[13];
extern VisibleEntryList *g_apCombat_zone_actor_lists[9];
extern short g_nCombat_zone_count;
extern unsigned char g_abOpenZoneTileX[9];
extern unsigned char g_abOpenZoneTileY[9];
extern long g_lZoneDefaultZ;
extern unsigned short g_wZoneDefaultYaw;
extern unsigned short g_wCurrentSaveSlotKey;
extern unsigned short g_wCurrentSaveFileKey;
extern int g_wBookmarkFmapX;
extern int g_wBookmarkFmapY;
extern unsigned short g_wBookmarkCompassIcon;
extern char g_szSaveSlotDirName_51cc[13];
extern unsigned char g_abSaveFileHeader[90];
extern unsigned short g_wExploreCameraYawSaved;
extern long g_lWorldZMin;
extern long g_lWorldZMax;
extern long g_lWorldZStep;
extern long g_lExploreCameraZSaved;
extern MenuPage *g_pReqMapPage;
extern unsigned char g_bssgap_5154[6];
extern short g_nSpellCount;
extern unsigned char g_bssgap_5150[2];
extern SpellDef *g_pSpellDefs;
extern char *g_szSpellNameBlob;
extern SpellDocRow *g_pSpellDocRows;
extern unsigned char far *g_pSpellDocBlob;
extern StatusEffectSlot *g_pStatusEffectPool;
extern unsigned char far *g_pSpellScreenBuffer;
extern ImageRecord **g_pCastfaceSpriteTable;
extern unsigned short *g_pSpellCastableScratch;
extern short g_nSnowParticleSeedX;
extern short g_nSpellFontSlot;
extern short g_nCombatTileEffectPending;
extern short g_nCombatTileX;
extern short g_nCombatTileY;
extern short g_nSpellSymbolCount;
extern SpellSymbolRecord *g_pSpellSymbolRecords;
extern short *g_pSpellSymbolX;
extern short *g_pSpellSymbolY;
extern unsigned char g_bssgap_5128[2];
extern CombatActor *g_combat_actors_B;
extern AnimSlot *g_anim_pool_B;
extern int g_combat_count_B;
extern unsigned char g_bssgap_511e[4];
extern CombatActor *g_actors_B_origin;
extern short g_chapter_roster[7];
extern ImageRecord **g_abCombatInnerPoolB[7][11];
extern char g_combat_save_filename[14];
extern unsigned short g_inner_pool_B;
extern CombatActor *g_current_actor;
extern CombatActor *g_picked_actor;
extern unsigned short g_acting_actor_speed;
extern int g_grid_tile_size;
extern short g_cursor_tile_x;
extern short g_cursor_tile_y;
extern unsigned short g_wInCombatMode;
extern MenuPage *g_combat_menu;
extern MenuPage *g_shoot_menu;
extern unsigned short g_combat_menu_selected_item;
extern unsigned short g_combat_menu_current_page;
extern short g_nCurrentQuarrelKindIdx;
extern unsigned short g_combat_cancelled;
extern unsigned short g_combat_music_handle;
extern CombatActor *g_acting_actor;
extern unsigned short g_traps_loaded_flag;
extern unsigned short g_encounter_id;
extern CombatActor *g_pCombatActiveActors;
extern AnimSlot *g_pCombatActiveAnimPool;
extern int g_nCombatActiveCount;
extern CombatActor *g_pCombatOtherActors;
extern AnimSlot *g_pCombatOtherAnimPool;
extern int g_nCombatOtherCount;
extern ImageRecord **g_combat_sprites;
extern ImageRecord **g_parch_bmx;
extern ImageRecord **g_combat_render_table_prev;
extern int g_combat_count_A;
extern CombatActor *g_combat_actors_A;
extern AnimSlot *g_anim_pool_A;
extern unsigned char g_bssgap_5028[2];
extern CombatActor **g_active_combatants;
extern ImageRecord **g_aCombatInnerPool[7][11];
extern CombatResCacheCol g_aCombatResCacheKindFlag;
extern CombatResCacheCol g_aCombatResCacheRefcount;
extern unsigned short g_aCombatResCacheKey[8];
extern ImageRecord **g_aCombatResCacheValue[8][3];
extern short g_nInvSelItemAnchorX;
extern short g_nInvSelItemAnchorY;
extern short g_nInvSelItemIconDx;
extern short g_nInvSelItemIconDy;
extern short g_nCursorSaveRectX;
extern short g_nCursorSaveRectY;
extern unsigned short g_inventory_actor_kind;
extern unsigned short g_dialog_anim_channel;
extern char g_speaker_kinds[6];
extern char g_speaker_names[6][32];
extern short g_nDialogAnchorX;
extern short g_nDialogAnchorY;
extern short g_nVisibleEntryCount;
extern unsigned short g_wVisibleEntrySegment;
extern unsigned short *g_pwVisibleEntryOffsets;
extern long g_aFilterTable[43];
extern long *g_pVisibleEntryDistances;
extern unsigned short g_wTimerTickRegistrySlot;
extern short g_nWorldViewYawNormal;
extern short g_nWorldViewYawChapter;
extern short g_nWorldViewFovNormal;
extern unsigned char g_bssgap_4c53;
extern unsigned char g_nWorldViewFovChapter;
extern unsigned short g_nVfxParticleColor;
extern VfxRec *g_pVfxVelocityPool;
extern unsigned short g_wVfxActiveParticleCount;
extern unsigned short g_nVfxParticleBurstOriginY;
extern SavedClipRect g_savedClip;
extern unsigned char g_bssgap_4c34[2];
extern GridCombatant *g_combatant_table;
extern short g_combatant_count;
extern CombatTile g_combat_tile_grid[8][13];
extern int g_nCombatTerrainWallColor;
extern unsigned char g_combat_move_map[8][13];
extern CursorState g_cursor_prev_x[2];
extern unsigned char far *g_pActiveCursorBuf;
extern unsigned char far *g_pCursorScratchBuf1;
extern unsigned char far *g_pCursorScratchBuf2;
extern unsigned short g_spriteBankCount;
extern PagedArrayEntry *g_spriteBanks;
extern ImageRecord *g_pBillboardSpriteImg;
extern short g_nBillboardScrX;
extern short g_nBillboardScrY;
extern short g_nBillboardW;
extern short g_nBillboardH;
extern unsigned short g_nFogRemapTableCount;
extern unsigned short g_wSpriteFogBucketWidth;
extern unsigned long g_lSpriteFogOnsetDist;
extern long g_lSpriteFogFarDist;
extern unsigned short g_nLodBucketWidth;
extern unsigned long g_dwLodNearThreshold;
extern unsigned long g_lFarCullDist;
extern unsigned char g_bssgap_4863[3];
extern GameState g_gameState;
extern unsigned short g_bPaletteCycleEbActive;
extern unsigned short g_wVgaScratchPageBase;
extern unsigned short g_wGameFontSlot;
extern unsigned short *g_pSkyPanoAssetTable;
extern WorldEntity *g_render_camera_scratch;
extern ViewContext *g_active_window;
extern unsigned short g_nChapterAtLoopExit;
extern unsigned char g_font_underline_offset[20];
extern int far *g_font_glyph_offset_table[20];
extern unsigned char far *g_font_width_table[20];
extern unsigned char far *g_font_bitmap_data[20];
extern unsigned char g_font_format[20];
extern unsigned long g_timer_ticks;
extern unsigned long g_dwSysTickCount;

extern unsigned short g_wGfxBlitDstPage;

extern void(far *g_pfn_blit_stretched)(void);

#endif
